# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b746dc58d1768dbac7917dbba7f22a66491382707ba448272792fd3ba73ad5ae88d8c4a937c39abc6176b32d5bf887d0ac0395e2d57e273def2cc2203f6d3233

test:
  secret_key_base: 4c885b3c655f357732e9a1778fda4e3edb884f394d8046a01fa01f60b09fcc090be334e473f5abf62e7bba3d8d6edcfa35806e27c07a9355ac4d1cdf631bd0c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
